[general]
enable_bucket = true

[[datasets]]
resolution = 1024
batch_size = 1

  [[datasets.subsets]]
  image_dir = "D:/program/chat/tools/lora_studio/dataset/25_kairi"
  class_tokens = "kairi 1girl"
  num_repeats = 15